#!/usr/bin/env bash
# Runs on every Codespace start via devcontainer.json postStartCommand.
#
# Five stages, each idempotent:
#   1. Self-heal: if neither prototype/.venv/bin/streamlit nor a system
#      streamlit on PATH exists, re-run .devcontainer/post_create.sh. This
#      covers the edge case where postCreateCommand was skipped or half
#      succeeded on a previous rebuild.
#   2. Refresh the Streamlit config in the user profile so port 8501 stays
#      pinned even if the user tampered with ~/.streamlit/config.toml.
#   3. Write a terminal banner script to ~/.vbi_banner.sh. The banner is
#      re-generated on every start so content changes propagate without
#      touching the user's .bashrc. It prints app status, forwarded URL,
#      log file location, and restart instructions on every new interactive
#      shell, so any new terminal is self-describing.
#   4. Ensure ~/.bashrc sources the banner file exactly once, and clean up
#      any legacy VBI_APP_URL_BANNER lines from earlier devcontainer
#      versions so users do not see stacked banners after an update.
#   5. Launch Streamlit as a fully detached background process via `nohup`.
#      Plain `( ... ) &` was not enough: the postStartCommand shell could
#      send SIGHUP to its children on exit and silently kill Streamlit
#      right after launch. `nohup` ignores SIGHUP, the `&` puts it in the
#      background, and `disown` removes it from the shell's job table so
#      no shutdown hook can reach it. Output is redirected to
#      /tmp/streamlit.log with a UTC timestamp marker at each start so
#      stale and fresh log data are distinguishable.

export PATH="$HOME/.local/bin:$PATH"

# Stage 1: self-heal. If no streamlit binary exists, re-run the full
# bootstrap. This is the last line of defence for a broken postCreateCommand.
if [ ! -x prototype/.venv/bin/streamlit ] && ! command -v streamlit >/dev/null 2>&1; then
    echo "post_start: no streamlit binary found, re-running post_create.sh"
    bash .devcontainer/post_create.sh || echo "post_start: post_create.sh failed, continuing anyway"
fi

# Stage 2: refresh Streamlit config.
mkdir -p ~/.streamlit
cp prototype/.streamlit/config.toml ~/.streamlit/config.toml

# Stage 3: write the banner file, rewritten on every start so content
# updates from future commits propagate without editing .bashrc by hand.
cat > ~/.vbi_banner.sh << 'BANNEREOF'
# Auto-generated by devcontainer/post_start.sh. Do not edit by hand.
# This file is rewritten on every Codespace start.
_vbi_url="https://${CODESPACE_NAME}-8501.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
if timeout 1 bash -c "</dev/tcp/localhost/8501" 2>/dev/null; then
    _vbi_status="running"
else
    _vbi_status="not running yet (check /tmp/streamlit.log for errors)"
fi
echo "========================================================================"
echo " Vibe Innovation Lab Codespace"
echo "========================================================================"
echo " What happened: Streamlit was started automatically at Codespace boot,"
echo "                as a detached background process bound to port 8501."
echo ""
echo " View the app:  Click the globe icon next to port 8501 in the PORTS"
echo "                panel below, or open the App URL in a new browser tab."
echo ""
echo " App URL:       ${_vbi_url}"
echo " Port status:   ${_vbi_status}"
echo ""
echo " Log file:      /tmp/streamlit.log"
echo " Live logs:     tail -f /tmp/streamlit.log"
echo ""
echo " Restart:       pkill -f 'streamlit run'"
echo "                cd prototype && .venv/bin/streamlit run app.py"
echo "========================================================================"
unset _vbi_url _vbi_status
BANNEREOF

# Stage 4: ensure .bashrc sources the banner exactly once, and clean up
# any legacy single-line banner from earlier devcontainer versions.
if [ -f ~/.bashrc ]; then
    # Delete the legacy VBI_APP_URL_BANNER marker line and the echo line
    # that follows it. No-op if the legacy markers are absent.
    sed -i '/# VBI_APP_URL_BANNER/,+1d' ~/.bashrc
fi
grep -q 'source ~/.vbi_banner.sh' ~/.bashrc 2>/dev/null || echo 'source ~/.vbi_banner.sh' >> ~/.bashrc

# Stage 5: launch Streamlit as a fully detached background process.
#
# Detachment strategy:
#   - nohup:   ignores SIGHUP so the process survives the postStartCommand
#              shell exit. Plain `&` is not enough because the parent shell
#              can send SIGHUP to its children on exit depending on the
#              huponexit setting.
#   - `&`:     puts it in the background so this script returns immediately.
#   - disown:  removes the job from the shell's job table so no later
#              cleanup hook can reach it by job id.
#   - stdin </dev/null: frees the controlling terminal.
#
# Binary resolution is ordered by decreasing reliability:
#   1. prototype/.venv/bin/streamlit: the uv-managed venv binary, present
#      when postCreateCommand successfully ran `uv sync`. Bypasses `uv run`
#      entirely and avoids the "Failed to spawn streamlit" error we hit
#      when `uv run` skipped the implicit sync.
#   2. system streamlit on PATH: the pip-fallback case where the
#      postCreateCommand fell back to `pip install -r requirements.txt`
#      into the image's system Python.
#   3. error log only: stage 1 self-heal already attempted to install
#      streamlit, so reaching this branch means a hard install failure.

echo "--- Streamlit auto-start at $(date -u +%Y-%m-%dT%H:%M:%SZ) ---" > /tmp/streamlit.log
if [ -x prototype/.venv/bin/streamlit ]; then
    echo "launching via prototype/.venv/bin/streamlit" >> /tmp/streamlit.log
    nohup bash -c 'cd prototype && exec .venv/bin/streamlit run app.py' \
        >> /tmp/streamlit.log 2>&1 </dev/null &
    disown
elif command -v streamlit >/dev/null 2>&1; then
    echo "launching via system streamlit on PATH" >> /tmp/streamlit.log
    nohup bash -c 'cd prototype && exec streamlit run app.py' \
        >> /tmp/streamlit.log 2>&1 </dev/null &
    disown
else
    echo "no streamlit binary available, app will not start" >> /tmp/streamlit.log
    echo "run: bash .devcontainer/post_create.sh" >> /tmp/streamlit.log
fi
