#!/usr/bin/env bash
# Runs on every Codespace start via devcontainer.json postStartCommand.
#
# Output mirroring: all stdout and stderr go to /tmp/vbi_start.log via an
# `exec` redirect. We do not also tee to stdout because postStartCommand
# runs non-interactively and its stdout is not shown anywhere prominent.
# The banner written in stage 3 points users at this file.
#
# Five stages, each idempotent:
#   1. Self-heal: if neither prototype/.venv/bin/streamlit nor a system
#      streamlit on PATH exists, re-run .devcontainer/post_create.sh. This
#      covers the edge case where postCreateCommand was skipped or half
#      succeeded on a previous rebuild.
#   2. Refresh the Streamlit config in the user profile so port 8501 stays
#      pinned even if the user tampered with ~/.streamlit/config.toml.
#   3. Write a terminal banner script to ~/.vbi_banner.sh. The banner is
#      re-generated on every start so content changes propagate without
#      touching the user's .bashrc. It prints a dynamic component status
#      report on every new interactive shell, so any new terminal is
#      self-describing even if something is broken.
#   4. Ensure ~/.bashrc sources the banner file exactly once, and clean up
#      any legacy VBI_APP_URL_BANNER lines from earlier devcontainer
#      versions so users do not see stacked banners after an update.
#   5. Launch Streamlit as a fully detached background process via `nohup`.
#      `( ... ) &` was not enough on its own: the postStartCommand shell
#      could send SIGHUP to its children on exit and silently kill
#      Streamlit right after launch. `nohup` ignores SIGHUP, `&` puts it
#      in the background, `disown` removes it from the shell's job table,
#      and `</dev/null` frees the controlling terminal. Output is
#      redirected to /tmp/streamlit.log with a UTC timestamp marker at
#      each start so stale and fresh log data are distinguishable.

exec > /tmp/vbi_start.log 2>&1
set -x

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

echo "=== post_start.sh starting at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "cwd: $(pwd)"
echo "PATH: $PATH"

# Stage 1: self-heal. If no streamlit binary exists, re-run the full
# bootstrap. Last line of defence for a broken postCreateCommand.
if [ ! -x prototype/.venv/bin/streamlit ] && ! command -v streamlit >/dev/null 2>&1; then
    echo "post_start: no streamlit binary found, re-running post_create.sh"
    bash .devcontainer/post_create.sh || echo "post_start: post_create.sh failed, continuing anyway"
fi

# Stage 2: refresh Streamlit config.
mkdir -p ~/.streamlit
cp prototype/.streamlit/config.toml ~/.streamlit/config.toml || \
    echo "WARN: could not copy prototype/.streamlit/config.toml"

# Stage 3: write the banner file, rewritten on every start so content
# updates from future commits propagate without editing .bashrc by hand.
# We use an unquoted heredoc so that _vbi_repo is interpolated at write
# time, baking the absolute workspace path into the banner. All other
# $-expressions are escaped with a backslash so they evaluate at shell
# source time, giving the banner a fresh component status on every new
# interactive shell.
_vbi_repo="${CODESPACE_VSCODE_FOLDER:-$(pwd)}"
cat > ~/.vbi_banner.sh << BANNEREOF
# Auto-generated by devcontainer/post_start.sh. Do not edit by hand.
# Re-generated on every Codespace start. Baked workspace path: ${_vbi_repo}
_vbi_repo="${_vbi_repo}"
_vbi_url="https://\${CODESPACE_NAME}-8501.\${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

echo "========================================================================"
echo " Vibe Innovation Lab Codespace"
echo "========================================================================"
echo ""
echo " Component status"
echo " ----------------"

if command -v uv >/dev/null 2>&1; then
    printf "   uv:              %s\n" "\$(uv --version 2>&1 | head -1)"
else
    printf "   uv:              NOT INSTALLED\n"
fi

if [ -x "\${_vbi_repo}/prototype/.venv/bin/streamlit" ]; then
    printf "   venv streamlit:  %s\n" "\$(\${_vbi_repo}/prototype/.venv/bin/streamlit --version 2>&1 | head -1)"
elif [ -d "\${_vbi_repo}/prototype/.venv" ]; then
    printf "   venv streamlit:  venv exists but streamlit missing\n"
else
    printf "   venv streamlit:  NOT CREATED\n"
fi

if command -v streamlit >/dev/null 2>&1; then
    printf "   sys streamlit:   %s\n" "\$(streamlit --version 2>&1 | head -1)"
else
    printf "   sys streamlit:   not on PATH\n"
fi

if command -v claude >/dev/null 2>&1; then
    printf "   claude code:     installed at \$(command -v claude)\n"
else
    printf "   claude code:     not installed\n"
fi

if timeout 1 bash -c "</dev/tcp/localhost/8501" 2>/dev/null; then
    printf "   port 8501:       OPEN (app running)\n"
else
    printf "   port 8501:       closed (app not running, check /tmp/streamlit.log)\n"
fi

echo ""
echo " App URL:         \${_vbi_url}"
echo ""
echo " Logs (cat any of these to see what actually happened)"
echo " -----------------------------------------------------"
for f in /tmp/vbi_bootstrap.log /tmp/vbi_start.log /tmp/streamlit.log; do
    if [ -f "\$f" ]; then
        printf "   %-26s  last modified: %s\n" "\$f" "\$(stat -c '%y' "\$f" 2>/dev/null | cut -d. -f1)"
    else
        printf "   %-26s  (missing)\n" "\$f"
    fi
done

echo ""
echo " Quick commands"
echo " --------------"
echo "   cat /tmp/vbi_bootstrap.log              # install-time log"
echo "   cat /tmp/vbi_start.log                  # start-time log"
echo "   tail -f /tmp/streamlit.log              # live app log"
echo "   bash .devcontainer/post_create.sh       # re-run install"
echo "   bash .devcontainer/post_start.sh        # re-run start"
echo "   pkill -f 'streamlit run'                # stop the app"
echo "   cd prototype && .venv/bin/streamlit run app.py  # manual start"
echo "========================================================================"
unset _vbi_url
BANNEREOF

# Stage 4: ensure .bashrc sources the banner exactly once, and clean up
# any legacy single-line banner from earlier devcontainer versions.
if [ -f ~/.bashrc ]; then
    sed -i '/# VBI_APP_URL_BANNER/,+1d' ~/.bashrc
fi
grep -q 'source ~/.vbi_banner.sh' ~/.bashrc 2>/dev/null || echo 'source ~/.vbi_banner.sh' >> ~/.bashrc

# Stage 5: launch Streamlit as a fully detached background process.
echo "--- Streamlit auto-start at $(date -u +%Y-%m-%dT%H:%M:%SZ) ---" > /tmp/streamlit.log
if [ -x prototype/.venv/bin/streamlit ]; then
    echo "launching via prototype/.venv/bin/streamlit" >> /tmp/streamlit.log
    nohup bash -c 'cd prototype && exec .venv/bin/streamlit run app.py' \
        >> /tmp/streamlit.log 2>&1 </dev/null &
    disown
elif command -v streamlit >/dev/null 2>&1; then
    echo "launching via system streamlit on PATH" >> /tmp/streamlit.log
    nohup bash -c 'cd prototype && exec streamlit run app.py' \
        >> /tmp/streamlit.log 2>&1 </dev/null &
    disown
else
    echo "no streamlit binary available, app will not start" >> /tmp/streamlit.log
    echo "run: bash .devcontainer/post_create.sh" >> /tmp/streamlit.log
fi

sleep 1
echo "=== post_start.sh finished at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "=== streamlit processes ==="
ps aux | grep -E 'streamlit|nohup' | grep -v grep || echo "no streamlit processes found"
exit 0
