#!/usr/bin/env bash
# Runs on every Codespace start via devcontainer.json postStartCommand.
#
# Four stages, each idempotent:
#   1. Refresh the Streamlit config in the user profile so port 8501 stays
#      pinned even if the user tampered with ~/.streamlit/config.toml.
#   2. Write a terminal banner script to ~/.vbi_banner.sh. The banner is
#      re-generated on every start so content changes propagate without
#      touching the user's .bashrc. It prints app status, forwarded URL,
#      log file location, and restart instructions on every new interactive
#      shell, so any new terminal is self-describing.
#   3. Ensure ~/.bashrc sources the banner file exactly once, and clean up
#      any legacy VBI_APP_URL_BANNER lines from earlier devcontainer
#      versions so users do not see stacked banners after an update.
#   4. Launch Streamlit as an orphaned background process. The (... &)
#      subshell pattern returns in milliseconds so postStartCommand
#      completes quickly and VS Code considers the start phase done.
#      Output is redirected to /tmp/streamlit.log with a UTC timestamp
#      marker at each start so stale and fresh log data are distinguishable.

# Stage 1: refresh Streamlit config.
mkdir -p ~/.streamlit
cp prototype/.streamlit/config.toml ~/.streamlit/config.toml

# Stage 2: write the banner file, rewritten on every start so content
# updates from future commits propagate without editing .bashrc by hand.
cat > ~/.vbi_banner.sh << 'BANNEREOF'
# Auto-generated by devcontainer/post_start.sh. Do not edit by hand.
# This file is rewritten on every Codespace start.
_vbi_url="https://${CODESPACE_NAME}-8501.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
if timeout 1 bash -c "</dev/tcp/localhost/8501" 2>/dev/null; then
    _vbi_status="running"
else
    _vbi_status="not running yet (check /tmp/streamlit.log for errors)"
fi
echo "========================================================================"
echo " Vibe Innovation Lab Codespace"
echo "========================================================================"
echo " What happened: Streamlit was started automatically at Codespace boot,"
echo "                as a background process bound to port 8501."
echo ""
echo " View the app:  Auto-opened in the Simple Browser panel inside VS Code."
echo "                To open in an external browser tab, click the globe"
echo "                icon next to port 8501 in the PORTS panel below."
echo ""
echo " App URL:       ${_vbi_url}"
echo " Port status:   ${_vbi_status}"
echo ""
echo " Log file:      /tmp/streamlit.log"
echo " Live logs:     tail -f /tmp/streamlit.log"
echo ""
echo " Restart:       pkill -f 'streamlit run'"
echo "                cd prototype && uv run streamlit run app.py"
echo "========================================================================"
unset _vbi_url _vbi_status
BANNEREOF

# Stage 3: ensure .bashrc sources the banner exactly once, and clean up
# any legacy single-line banner from earlier devcontainer versions.
if [ -f ~/.bashrc ]; then
    # Delete the legacy VBI_APP_URL_BANNER marker line and the echo line
    # that follows it. No-op if the legacy markers are absent.
    sed -i '/# VBI_APP_URL_BANNER/,+1d' ~/.bashrc
fi
grep -q 'source ~/.vbi_banner.sh' ~/.bashrc 2>/dev/null || echo 'source ~/.vbi_banner.sh' >> ~/.bashrc

# Stage 4: launch Streamlit in the background. The outer subshell is
# backgrounded from this parent script via the trailing &, which lets
# post_start.sh return in milliseconds while Streamlit continues to run
# as an orphaned process with its output captured in /tmp/streamlit.log.
#
# Binary resolution is ordered by decreasing reliability:
#   1. prototype/.venv/bin/streamlit: the uv-managed venv binary, present
#      when postCreateCommand successfully ran `uv sync`. This bypasses
#      `uv run` entirely and avoids the "Failed to spawn streamlit" error
#      we hit when `uv run` skipped the implicit sync.
#   2. system streamlit on PATH: the pip-fallback case where the
#      postCreateCommand OR fell back to `pip install -r requirements.txt`
#      into the image's system Python.
#   3. `uv sync` then venv binary: bootstrap path if neither exists. A
#      fresh sync guarantees the venv is populated before invocation.
(
    export PATH="$HOME/.local/bin:$PATH"
    echo "--- Streamlit auto-start at $(date -u +%Y-%m-%dT%H:%M:%SZ) ---" > /tmp/streamlit.log
    cd prototype || exit 1
    if [ -x .venv/bin/streamlit ]; then
        echo "launching via prototype/.venv/bin/streamlit" >> /tmp/streamlit.log
        .venv/bin/streamlit run app.py >> /tmp/streamlit.log 2>&1
    elif command -v streamlit >/dev/null 2>&1; then
        echo "launching via system streamlit on PATH" >> /tmp/streamlit.log
        streamlit run app.py >> /tmp/streamlit.log 2>&1
    elif command -v uv >/dev/null 2>&1; then
        echo "no streamlit binary found, running uv sync then launching" >> /tmp/streamlit.log
        uv sync >> /tmp/streamlit.log 2>&1
        if [ -x .venv/bin/streamlit ]; then
            .venv/bin/streamlit run app.py >> /tmp/streamlit.log 2>&1
        else
            echo "uv sync finished but .venv/bin/streamlit still missing" >> /tmp/streamlit.log
        fi
    else
        echo "no streamlit and no uv available" >> /tmp/streamlit.log
    fi
) &
